//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KawaiiHTTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KawaiiHTTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder {
            get {
                object obj = ResourceManager.GetObject("appbar_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_ellipsis {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_ellipsis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_lock {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_open {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_people {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_people", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_puzzle {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_puzzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_folder_star {
            get {
                object obj = ResourceManager.GetObject("appbar_folder_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appbar_page_bold {
            get {
                object obj = ResourceManager.GetObject("appbar_page_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;#filename&lt;/title&gt;
        ///		&lt;link href=&quot;/~kawaiicore/resource/CoreCSS.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot;&gt;
        ///		&lt;!-- link href=&quot;CoreCSS.css&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; --&gt;
        ///	&lt;/head&gt;
        ///	
        ///	&lt;body&gt;
        ///		&lt;div class = &quot;browser-head&quot;&gt;
        ///			&lt;div class = &quot;kawaii-logo&quot;&gt;Kawaii HTTP&lt;/div&gt;
        ///			&lt;div class = &quot;filename-space&quot;&gt;#filename&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		
        ///		&lt;div class = &quot;browser-container&quot;&gt;
        ///			&lt;table class = &quot;browser-table&quot;&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;fileicon-false&quot;&gt;&lt;/td&gt;&lt;td&gt;&lt;a href=&quot;#p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrowserPage {
            get {
                return ResourceManager.GetString("BrowserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;fileicon-#isfile&quot;&gt;&lt;div&gt;&lt;/div&gt;&lt;/td&gt;&lt;td&gt;&lt;a href=&quot;#location&quot;&gt;#display&lt;/a&gt;&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string BrowserRowTemplate {
            get {
                return ResourceManager.GetString("BrowserRowTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///#8d7374
        ///#f9e4f7
        ///#d8b7d4
        ///#875698
        ///#6b3b61
        ///*/
        ///
        ///@font-face {
        ///	font-family: ubuntu;
        ///	src: url(&apos;Ubuntu-R.ttf&apos;);
        ///}
        ///
        ///body, html {
        ///	font-family: ubuntu;
        ///	background-color: #f9e4f7;
        ///	color: #875698;
        ///}
        ///
        ///a {
        ///	color: #875698;
        ///	margin: 0;
        ///	padding: 7px  0 7px 5px;
        ///	width: 100%;
        ///	height: 100%;
        ///	display: inline-block;
        ///}
        ///a:visited { color: #6b3b61; }
        ///tr:hover a, a:hover, a:active {  color: #d8b7d4; }
        ///
        ///.browser-head {
        ///	position: absolute;
        ///	left: 0;
        ///	top: 0;
        ///	width: 100%;
        ///	height: 50px;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreCSS {
            get {
                return ResourceManager.GetString("CoreCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atom application/atom+xml
        ///dart application/dart
        ///es application/ecmascript
        ///js application/javascript
        ///edi application/EDI-X12
        ///edf application/EDIFACT
        ///json application/json
        ///bin application/octet-stream
        ///ogg application/ogg
        ///pdf application/pdf
        ///ps application/postscript
        ///rdf application/rdf+xml
        ///rss application/rss+xml
        ///soap application/soap+xml
        ///font application/font-woff
        ///xhtml application/xhtml+xml
        ///! xml application/xml
        ///dtd application/xml-dtd
        ///xop application/xop+xml
        ///zip application/zip
        ///gzip app [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MIME {
            get {
                return ResourceManager.GetString("MIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ubuntu_R {
            get {
                object obj = ResourceManager.GetObject("Ubuntu_R", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
